name: Release

on:
  push:
    branches:
      - main
      - master

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Set up Python
        uses: actions/setup-python@v4.7.1
        with:
          python-version: "3.14"

      - name: Install uv
        run: |
          pip install uv
          uv --version

      - name: Check if there is a parent commit
        id: check-parent-commit
        run: |
          echo "::set-output name=sha::$(git rev-parse --verify --quiet HEAD^)"

      - name: Detect and tag new version
        id: check-version
        if: steps.check-parent-commit.outputs.sha
        uses: salsify/action-detect-and-tag-new-version@v2.0.1
        with:
          version-command: |
            python -c "import tomllib; print(tomllib.load(open('pyproject.toml', 'rb'))['project']['version'])"

      - name: Install build dependencies
        if: "! steps.check-version.outputs.tag"
        run: |
          uv pip install --system tomlkit

      - name: Bump version for developmental release
        if: "! steps.check-version.outputs.tag"
        shell: python
        run: |
          import tomlkit
          import time
          from pathlib import Path

          path = Path("pyproject.toml")
          with path.open("r", encoding="utf-8") as f:
              data = tomlkit.load(f)

          version = data["project"]["version"]
          parts = version.split(".")
          parts[-1] = str(int(parts[-1]) + 1)
          new_base = ".".join(parts)

          dev_version = f"{new_base}.dev.{int(time.time())}"

          data["project"]["version"] = dev_version
          with path.open("w", encoding="utf-8") as f:
              tomlkit.dump(data, f)
          print(f"Bumped version to {dev_version}")

      - name: Build package
        run: |
          uv build

      - name: Publish package on PyPI
        if: steps.check-version.outputs.tag
        uses: pypa/gh-action-pypi-publish@v1.5.0
        with:
          user: __token__
          password: ${{  secrets.PYPI_TOKEN }}

      - name: Publish package on TestPyPI
        if: "! steps.check-version.outputs.tag"
        uses: pypa/gh-action-pypi-publish@v1.5.0
        with:
          user: __token__
          password: ${{  secrets.TEST_PYPI_TOKEN }}
          repository_url: https://test.pypi.org/legacy/

      - name: Publish the release notes
        uses: release-drafter/release-drafter@v5.20.0
        with:
          publish: ${{  steps.check-version.outputs.tag != '' }}
          tag: ${{  steps.check-version.outputs.tag }}
        env:
          GITHUB_TOKEN: ${{  secrets.GITHUB_TOKEN }}
